### ISSUE TITLE
Diagrama backend

### ISSUE THREAD

**Issue by MauricioMachadoFF** [UNB-PI2-Grupo3-BracoRobotico/Documentation#34]

**Comment by fmaachadoo** [comment]
![Diagrama de Pacotes drawio (1)](https://github.com/UNB-PI2-Grupo3-BracoRobotico/Documentation/assets/40258400/86395889-c327-457b-bdc8-5c14cbd26b61)

**Comment by fmaachadoo** [comment]
Está aqui o esboço do novo diagrama de pacotes, irei colocar em uma branch no local correto e com as descrições amanhã.
Aguardo sugestões
@MauricioMachadoFF

**Comment by fmaachadoo** [comment]
- Imports para o DatabaseController
- API para o admin_service

**Comment by fmaachadoo** [comment]
Single source of truth

**Comment by fmaachadoo** [comment]
@MauricioMachadoFF o `BusinessInteligence` é o pacote que vai preparar os dados para enviar pras telas onde mostram dados estatísticos sobre as vendas...

**Comment by fmaachadoo** [comment]
![Diagrama de Pacotes drawio (2)](https://github.com/UNB-PI2-Grupo3-BracoRobotico/Documentation/assets/40258400/3e61d654-6fa8-4d2f-a7e6-ce807530c3b4)
